### ISSUE TITLE
UCF data problem

### ISSUE THREAD

**Issue by baochenfu** [Kay1794/Motion-Graph-Video-Prediction#2]
I downloaded the UCF data set you published, but I found that some video frames were missing, especially in Glof-Swing-Back. I hope to keep the data consistent with your work. Can you provide the original data set? We would appreciate it

**Comment by Kay1794** [comment]
Sorry for the confusion. The dataset split we provided in this repo is the original dataset. You should be able to directly use the data splits and compare with Motion graph and MMVP methods. 

For your missing frame question. Great one! We have filtered out some of the video seq/frames basically due to two reasons: 1. The resolution of the frames are not suitable for CenterCrop + Resize operations; 2. The frame rate is not consistent in the given video sequence, some of the video sequences have missing frames in the dataset.  

I have checked the Golf-Swing-Back seq in train.txt, may I know which frame(s) you think are missing?

**Comment by baochenfu** [comment]
In the UCF Sports dataset, there are no video frames under the Golf-Swing-Back folder, but in train.txt, jpg under /Golf-Swing-Back/ is used，such as : ucf_sports_actions/Golf-Swing-Back/001/3283-8_700741_042.jpg

**Comment by Kay1794** [comment]
Some of the image files are missing in the original downloaded dataset. For each video seq in the Golf-Swing-Back folder, we read and save 60 frames given the .avi file, e.g. /Golf-Swing-Back/001/3283-8_700741_000.jpg to /Golf-Swing-Back/001/3283-8_700741_059.jpg .

**Comment by baochenfu** [comment]
Thank you for your patience.
